### ISSUE TITLE
Type expected / Identifier Expected (Lacking Parameters)

### ISSUE THREAD

**Issue by alrosal** [MikeGriffinReborn/EntitySpaces_DotNetStandard#5]
Hi Mike,

First, here are the versions I have, if needed:
- EntitySpace Studio 2019.1.0828.0
- Visual Studio 2019
- .Net Core 3.0

I was generating from the C# template and got this error:
![image](https://user-images.githubusercontent.com/5661583/70442224-dce90580-1ad0-11ea-9d17-55ded90ecbad.png)

It seems that there were some lacking parameters.

I tried to remove the "," and set it only with the `esSqlAccessType sqlAccessType`  and it seems to compile fine. Need to test yet on runtime.

**Comment by trran** [comment]
Apparently you are not assigning a primary key to your table before generating it.

**Comment by alrosal** [comment]
> Apparently you are not assigning a primary key to your table before generating it.

Maybe you are right, some of these tables have no primary keys. We previously used the ES Studio 2009 version and maybe it wasn't able to detect those errors. I will check. Thank you!

**Comment by MikeGriffinReborn** [comment]
Yep, EntitySpaces needs Primary Keys otherwise it doesn't know how to update data. However, I suppose if you for some reason can't add a primary key you could comment those functions out and then just load it via that objects Query class ...
